# Numpy

In [1]:
import numpy as np

### Creating arrays from lists

In [11]:
array_1d = np.array([1, 2, 3, 4])
print(f'1D array is:')
print(array_1d)

array_2d = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8]])
print(f'2D array is:')
print(array_2d)

1D array is:
[1 2 3 4]
2D array is:
[[1 2 3 4]
 [5 6 7 8]]


### List vs numpyarray